### ISSUE TITLE
Add a way for it to have the option for .json and .txt files

### ISSUE THREAD

**Issue by AmedarW** [MaximumOverflow/Philia#5]
I've made a lora with this, I like it a lot, but it would be better to have the option to choose between .txt files or .json files. as captioning loras require .txt files

**Comment by MaximumOverflow** [comment]
Fun fact: that's a bug.
I have no idea why it's exporting them as json, it's not even valid json...

**Comment by MaximumOverflow** [comment]
Anyway, I fixed it. I'll include it in the next release.
